version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-broker
    ports:
      - "1883:1883"   # MQTT protocol
      # - "9001:9001"   # WebSocket protocol (optional, configure if needed)
    volumes:
      - ./mosquitto_config:/mosquitto/config
      - ./mosquitto_data:/mosquitto/data
      - ./mosquitto_logs:/mosquitto/log
    restart: unless-stopped